export type WebProject = {
  id: string;
  number: string;
  title: string;
  category: string;
  stack: string;
  description: string;
  image: string;
  demo: string;
};

export const webProjects: WebProject[] = [
  {
    id: "opopop-gifting",
    number: "01",
    title: "Opopop Gifting",
    category: "CORPORATE GIFTING EXPERIENCE",
    stack: "REPLO · SHOPIFY · FIGMA",
    description: "A dedicated gifting experience for Opopop, designed around bulk orders, customizable gifts, corporate occasions and a simple path from discovery to request.",
    image: "/assets/opopop.com_pages_gifting-page.png",
    demo: "https://opopop.com/pages/gifting-page",
  },
  {
    id: "hair-veda",
    number: "02",
    title: "Hair Veda",
    category: "BEAUTY & HAIRCARE E-COMMERCE",
    stack: "REPLO · SHOPIFY · PRODUCT PAGE",
    description: "A detailed product experience for Avani Hair Growth Oil, balancing ingredient storytelling, product benefits, subscription options and a focused purchase journey.",
    image: "/assets/hairveda.co.uk_products_avani-hair-growth-oil-50ml_variant=51100174418261.png",
    demo: "https://hairveda.co.uk/products/avani-hair-growth-oil-50ml",
  },
  {
    id: "gfuel",
    number: "03",
    title: "G FUEL",
    category: "ENERGY & GAMING E-COMMERCE",
    stack: "REPLO · SHOPIFY · PRODUCT EXPERIENCE",
    description: "A product-focused experience for G FUEL’s Starter Kit, bringing together subscription options, product benefits, flavor discovery and a free shaker offer.",
    image: "/assets/gfuel.com_pages_subscription-free-shaker-v4.png",
    demo: "https://gfuel.com/pages/subscription-free-shaker-v4",
  },
  {
    id: "hestan-culinary",
    number: "04",
    title: "Hestan Culinary",
    category: "CULINARY & COOKWARE BRAND",
    stack: "REPLO · SHOPIFY · BRAND STORYTELLING",
    description: "A brand-led experience built around Thomas Keller and Hestan cookware, combining chef storytelling, product discovery, recipes and featured collections.",
    image: "/assets/hestanculinary.com_pages_thomas-keller-hestan-culinary-brand-ambassador.png",
    demo: "https://hestanculinary.com/pages/thomas-keller-hestan-culinary-brand-ambassador",
  },
  {
    id: "dirty-gut",
    number: "05",
    title: "Dirty Gut",
    category: "FUNCTIONAL FOOD E-COMMERCE",
    stack: "REPLO · SHOPIFY · E-COMMERCE",
    description: "A playful e-commerce experience for probiotic chocolate, combining product discovery, everyday use cases, education and social proof.",
    image: "/assets/dirtygut.com_pages_home-page.png",
    demo: "https://dirtygut.com/pages/home-page",
  },
  {
    id: "tanaor",
    number: "06",
    title: "TANAOR",
    category: "JEWELRY & GIFTING E-COMMERCE",
    stack: "REPLO · SHOPIFY · STORYTELLING",
    description: "A long-form product story for TANAOR’s Nano-Bible Necklace, combining emotional gifting, product education, craftsmanship and social proof into a focused buying journey.",
    image: "/assets/tanaorjewelry.com_pages_lpt4.png",
    demo: "https://tanaorjewelry.com/pages/lpt4",
  },
  {
    id: "zacs-sweet-shop",
    number: "07",
    title: "Zac's Sweet Shop",
    category: "CHOCOLATE E-COMMERCE STOREFRONT",
    stack: "REPLO · SHOPIFY · FIGMA",
    description: "A playful e-commerce experience built for a handcrafted chocolate brand, balancing bold product storytelling with a smooth, gift-focused shopping journey.",
    image: "/assets/zacs-sweet-shop.myshopify.com_pages_home.png",
    demo: "https://zacs-sweet-shop.myshopify.com/pages/home",
  },
  {
    id: "neueve",
    number: "08",
    title: "NeuEve",
    category: "WOMEN'S HEALTH & WELLNESS",
    stack: "REPLO · SHOPIFY · LONG-FORM LANDING PAGE",
    description: "A long-form wellness experience focused on Lichen Sclerosus relief, combining education, product solutions, testimonials, FAQs and subscription journeys.",
    image: "/assets/www.neueve.com_pages_lichen-sclerosus-solution.png",
    demo: "https://www.neueve.com/pages/lichen-sclerosus-solution",
  },
  {
    id: "waxd",
    number: "09",
    title: "WAXD",
    category: "BRAND STORYTELLING & E-COMMERCE",
    stack: "REPLO · SHOPIFY · FIGMA",
    description: "An editorial brand experience introducing a cleaner alternative to traditional surf wax through storytelling, product education and a launch-focused journey.",
    image: "/assets/www.surfwaxd.com_pages_the-first-wave.png",
    demo: "https://www.surfwaxd.com/pages/the-first-wave",
  },
  {
    id: "merlins",
    number: "10",
    title: "Merlins",
    category: "PET WELLNESS E-COMMERCE",
    stack: "REPLO · SHOPIFY · PRODUCT EXPERIENCE",
    description: "A conversion-focused product experience for a feline wellness brand, combining product education, benefits, subscriptions and social proof into a clear shopping journey.",
    image: "/assets/merlinspets.com_products_salmonpowder_view=replo.93623e5e-2537-46ca-b644-4deffb1f7a44.png",
    demo: "https://merlinspets.com/products/salmonpowder?view=replo.93623e5e-2537-46ca-b644-4deffb1f7a44",
  },
  {
    id: "vitacup",
    number: "11",
    title: "VitaCup",
    category: "HEALTH & WELLNESS E-COMMERCE",
    stack: "REPLO · SHOPIFY · FIGMA",
    description: "A content-led product experience for VitaCup’s Slim Protein Coffee, combining product education, fitness-focused storytelling, recipes and social proof.",
    image: "/assets/www.vitacup.com_pages_5-reasons-why-slim-protein-coffee.png",
    demo: "https://www.vitacup.com/pages/5-reasons-why-slim-protein-coffee",
  },
  {
    id: "opopop",
    number: "12",
    title: "Opopop",
    category: "FOOD & BEVERAGE E-COMMERCE",
    stack: "REPLO · SHOPIFY · CONVERSION UX",
    description: "A high-energy popcorn shopping experience built around flavor discovery, product education, social proof and a customizable bundle-building journey.",
    image: "/assets/opopop.com_pages_og-fb-7b.png",
    demo: "https://opopop.com/pages/og-fb-7b",
  },
  {
    id: "djablo-sauce",
    number: "13",
    title: "Djablo Sauce",
    category: "FOOD & BEVERAGE BRAND",
    stack: "REPLO · SHOPIFY · BRAND EXPERIENCE",
    description: "A bold brand experience for Djablo Sauce, introducing its Filipino roots, inter-generational story and range of hot sauces through an expressive storefront.",
    image: "/assets/djablosauce.com_pages_homepage.png",
    demo: "https://djablosauce.com/pages/homepage",
  },
];
